### ISSUE TITLE
Add an after commit hook for updating repo

### ISSUE THREAD

**Issue by urlsangel** [gollum/gollum-lib#12]
I've been setting Gollum up on a little Debian box here so it can be used as a shared wiki resource. I'd like it to be able to accept wiki amends through either the web interface (a single centrally served one, not a localhost instance each), or through individual markdown edits and git commits.

For the web service to keep in sync though, I need it to do a pull/push on commit - I understand that this might create merge conflicts if someone else is editing that page at the same time, but I think the risk of that is low at the moment, and I can live with it.

I've created this gist of how I've hacked it to work at the moment:

https://gist.github.com/urlsangel/5411081

I also need some way for the server to pull the latest whenever a new session is started.

I'm a Ruby noob so am feeling my way along in this - any thoughts on what the best way to do this would be?

**Comment by dkozel** [comment]
The grit adapter has been updated. Here's the currently working hook with remote = origin and branch = master.

```
wiki = Gollum::Wiki.new(".")

Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
  wiki.repo.git.pull("origin", "master")
  wiki.repo.git.push("origin", "master")
end
```

**Comment by pinkeen** [comment]
The hook doesn't work for me. 

I want to run a bash script in post commit (creates a merge-request in case of conflicts). The problem is that the file being changed is modified but there's no commit yet - at least according to cli git. How is that possible? Is there a way to "sync" the git adapter changes before calling the hook?

**Comment by existme** [comment]
Actually the more correct way of doing this might be:

``` ruby
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
     committer.wiki.repo.git.pull('origin', committer.wiki.ref)
     committer.wiki.repo.git.push('origin', committer.wiki.ref)
end
```

So there would not be any need of creating an instance of wiki.

**Comment by pReya** [comment]
@existme Is this code only valid, when using the grit adapter? Any alternative for rugged?

**Comment by bartkamphorst** [comment]
@pReya @existme 's snippet should also work with the rugged adapter.

**Comment by jonthebastard** [comment]
I was pointed here via [this guide for syncing a GitHub wiki with Gollum](https://grantwinney.com/hosting-a-github-wiki-remotely-on-ubuntu/). When using @existme 's config as above, any attempt to create or edit pages will fail, with these errors:

1. If I try to edit a page, I get a popup of "Internal Server Error", with this error stack:

```
2020-06-29 01:49:24 - Rugged::NetworkError - unsupported URL protocol:
	/var/lib/gems/2.5.0/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb:319:in `fetch'
	/var/lib/gems/2.5.0/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb:319:in `pull'
	/home/punch/gollum_config.rb:8:in `block in <top (required)>'
	/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/hook.rb:28:in `block in execute'
	/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/hook.rb:27:in `each_value'
	/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/hook.rb:27:in `execute'
	/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/committer.rb:131:in `commit'
	/var/lib/gems/2.5.0/gems/gollum-5.0.1/lib/gollum/app.rb:337:in `block (2 levels) in <class:App>'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1636:in `block in compile!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (3 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1006:in `route_eval'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:987:in `block (2 levels) in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1035:in `block in process_route'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1033:in `process_route'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:985:in `block in route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `each'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:984:in `route!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1098:in `block in dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1095:in `dispatch!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `block in call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `block in invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `catch'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1072:in `invoke'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:919:in `call!'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:908:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb:18:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb:16:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb:26:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb:50:in `call'
	/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb:31:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb:22:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1951:in `call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `block in call'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1730:in `synchronize'
	/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1503:in `call'
	/var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
	/usr/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
	/usr/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
	/usr/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
69.209.96.25 - - [29/Jun/2020:01:49:24 UTC] "POST /gollum/edit/Home.md HTTP/1.1" 500 145099
http://64.225.41.26:4567/gollum/edit/Home.md -> /gollum/edit/Home.md
```

2. If I try to create a new page, I get the same error stack, and am redirected to the Sinatra error page for `Rugged::NetworkError at /gollum/create`. THAT has a much more detailed output, which is below:

<details><summary> <tt> Rugged::NetworkError at /gollum/create </tt> error page </summary>

```
application error
Rugged::NetworkError at /gollum/create
unsupported URL protocol
file: git_layer_rugged.rb location: fetch line: 319

BACKTRACE
/var/lib/gems/2.5.0/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb in fetch
        r.fetch(branches, options)
/var/lib/gems/2.5.0/gems/gollum-rugged_adapter-1.0/lib/rugged_adapter/git_layer_rugged.rb in pull
        r.fetch(branches, options)
/home/punch/gollum_config.rb in block in <top (required)>
  wiki.repo.git.pull("origin", "master")
/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/hook.rb in block in execute
            block.call(*args)
/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/hook.rb in each_value
          type_hooks.each_value do |block|
/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/hook.rb in execute
          type_hooks.each_value do |block|
/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/committer.rb in commit
      Hook.execute(:post_commit, self, sha1)
/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/wiki.rb in write
      multi_commit ? committer : committer.commit
/var/lib/gems/2.5.0/gems/gollum-lib-5.0.4/lib/gollum-lib/wiki.rb in write_page
     write(merge_path_elements(nil, path, format), data, commit)
/var/lib/gems/2.5.0/gems/gollum-5.0.1/lib/gollum/app.rb in block (2 levels) in <class:App>
          wiki.write_page(::File.join(path, name), format, params[:content], commit_message)
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
          proc { |a, p| unbound_method.bind(a).call }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in compile!
          proc { |a, p| unbound_method.bind(a).call }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block (3 levels) in route!
            route_eval { block[*args] }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in route_eval
      throw :halt, yield
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block (2 levels) in route!
            route_eval { block[*args] }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in process_route
        block ? block[self, values] : yield(self, values)
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in catch
      catch(:pass) do
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in process_route
      catch(:pass) do
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in route!
          returned_pass_block = process_route(pattern, conditions) do |*args|
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in each
        routes.each do |pattern, conditions, block|
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in route!
        routes.each do |pattern, conditions, block|
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in dispatch!
        route!
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in invoke
      res = catch(:halt) { yield }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in catch
      res = catch(:halt) { yield }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in invoke
      res = catch(:halt) { yield }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in dispatch!
      invoke do
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in call!
      invoke { dispatch! }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in invoke
      res = catch(:halt) { yield }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in catch
      res = catch(:halt) { yield }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in invoke
      res = catch(:halt) { yield }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call!
      invoke { dispatch! }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
      dup.call!(env)
/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/xss_header.rb in call
        status, headers, body = @app.call(env)
/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/path_traversal.rb in call
        app.call env
/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/json_csrf.rb in call
        status, headers, body = app.call(env)
/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb in call
        result or app.call(env)
/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/base.rb in call
        result or app.call(env)
/var/lib/gems/2.5.0/gems/rack-protection-2.0.8.1/lib/rack/protection/frame_options.rb in call
        status, headers, body        = @app.call(env)
/var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb in call
      @app.call(env)
/var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/head.rb in call
      status, headers, body = @app.call(env)
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/show_exceptions.rb in call
      @app.call(env)
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
      result, callback = app.call(env), env['async.callback']
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
      @stack.call(env)
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in block in call
        synchronize { prototype.call(env) }
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in synchronize
          yield
/var/lib/gems/2.5.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb in call
        synchronize { prototype.call(env) }
/var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb in service
        status, headers, body = @app.call(env)
/usr/lib/ruby/2.5.0/webrick/httpserver.rb in service
      si.service(req, res)
/usr/lib/ruby/2.5.0/webrick/httpserver.rb in run
          server.service(req, res)
/usr/lib/ruby/2.5.0/webrick/server.rb in block in start_thread
          block ? block.call(sock) : run(sock)
GET
No GET data.

POST
Variable  Value
content 
""
format  
"markdown"
keybinding  
"default"
message 
"Created testagain (markdown)"
page  
"testagain"
path  
"/"
COOKIES
No cookie data.

Rack ENV
Variable  Value
CONTENT_LENGTH  
108
CONTENT_TYPE  
application/x-www-form-urlencoded
GATEWAY_INTERFACE 
CGI/1.1
HTTP_ACCEPT 
text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
HTTP_ACCEPT_ENCODING  
gzip, deflate
HTTP_ACCEPT_LANGUAGE  
en-US,en;q=0.9
HTTP_CACHE_CONTROL  
max-age=0
HTTP_CONNECTION 
keep-alive
HTTP_HOST 
64.225.41.26:4567
HTTP_ORIGIN 
http://64.225.41.26:4567
HTTP_REFERER  
http://64.225.41.26:4567/gollum/create/testagain
HTTP_UPGRADE_INSECURE_REQUESTS  
1
HTTP_USER_AGENT 
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
HTTP_VERSION  
HTTP/1.1
PATH_INFO 
/gollum/create
QUERY_STRING  
REMOTE_ADDR 
69.209.96.25
REMOTE_HOST 
69.209.96.25
REQUEST_METHOD  
POST
REQUEST_PATH  
/gollum/create
REQUEST_URI 
http://64.225.41.26:4567/gollum/create
SCRIPT_NAME 
SERVER_NAME 
64.225.41.26
SERVER_PORT 
4567
SERVER_PROTOCOL 
HTTP/1.1
SERVER_SOFTWARE 
WEBrick/1.4.2 (Ruby/2.5.1/2018-03-29)
rack.errors 
#<Object:0x000055be8f8322e8>
rack.hijack 
#<Proc:0x00007fcf308b49d8@/var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb:83 (lambda)>
rack.hijack?  
true
rack.hijack_io  
nil
rack.input  
#<StringIO:0x00007fcf308b4a50>
rack.logger 
#<Rack::NullLogger:0x000055be91fd8450 @app=#<Rack::Protection::FrameOptions:0x000055be91fd84f0 @app=#<Rack::Protection::HttpOrigin:0x000055be91fd85b8 @app=#<Rack::Protection::IPSpoofing:0x000055be91fd8680 @app=#<Rack::Protection::JsonCsrf:0x000055be91fd8720 @app=#<Rack::Protection::PathTraversal:0x000055be91fd87c0 @app=#<Rack::Protection::XSSHeader:0x000055be91fd8888 @app=#<Precious::App:0x000055be92046040 @default_layout=:layout, @preferred_extension=nil, @app=nil, @template_cache=#<Tilt::Cache:0x000055be92045fa0 @cache={[:mustache, :layout]=>Precious::Views::Layout, [:mustache, :page]=>Precious::Views::Page, [:mustache, :create]=>Precious::Views::Create, [:mustache, :edit]=>Precious::Views::Edit}>>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :xss_mode=>:block, :nosniff=>true, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>true}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>true}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :allow_if=>nil, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>true}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>true}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :allow_if=>nil, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>true}>, @options={:reaction=>:drop_session, :logging=>true, :message=>"Forbidden", :encryptor=>Digest::SHA1, :session_key=>"rack.session", :status=>403, :allow_empty_referrer=>true, :report_key=>"protection.failed", :html_types=>["text/html", "application/xhtml", "text/xml", "application/xml"], :frame_options=>:sameorigin, :img_src=>"'self' data:", :font_src=>"'self'", :without_session=>true}, @frame_options="SAMEORIGIN">>
rack.multiprocess 
false
rack.multithread  
true
rack.request.cookie_hash  
{}
rack.request.form_hash  
{"page"=>"testagain", "path"=>"/", "keybinding"=>"default", "format"=>"markdown", "content"=>"", "message"=>"Created testagain (markdown)"}
rack.request.form_input 
#<StringIO:0x00007fcf308b4a50>
rack.request.form_vars  
page=testagain&path=%2F&keybinding=default&format=markdown&content=&message=Created+testagain+%28markdown%29
rack.request.query_hash 
{}
rack.request.query_string 
rack.run_once 
false
rack.session  
{}
rack.tempfiles  
[]
rack.url_scheme 
http
rack.version  
[1, 3]
sinatra.accept  
[#<Sinatra::Request::AcceptEntry:0x00007fcf308343f0 @entry="text/html", @type="text/html", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007fcf308342b0 @entry="application/xhtml+xml", @type="application/xhtml+xml", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007fcf3082fe90 @entry="image/webp", @type="image/webp", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007fcf3082fd50 @entry="image/apng", @type="image/apng", @params={}, @q=1.0>, #<Sinatra::Request::AcceptEntry:0x00007fcf3082f968 @entry="application/signed-exchange;v=b3;q=0.9", @type="application/signed-exchange", @params={"v"=>"b3"}, @q=0.9>, #<Sinatra::Request::AcceptEntry:0x00007fcf30834170 @entry="application/xml;q=0.9", @type="application/xml", @params={}, @q=0.9>, #<Sinatra::Request::AcceptEntry:0x00007fcf3082fc10 @entry="*/*;q=0.8", @type="*/*", @params={}, @q=0.8>]
sinatra.error 
#<Rugged::NetworkError: unsupported URL protocol>
sinatra.error.params  
{"page"=>"testagain", "path"=>"/", "keybinding"=>"default", "format"=>"markdown", "content"=>"", "message"=>"Created testagain (markdown)"}
sinatra.route 
POST /gollum/create
You're seeing this error because you have enabled the show_exceptions setting.
```

</details>

I'm unable to get this working, and could use some assistance (though I may be missing something very basic here).

**Comment by pReya** [comment]
@jonthebastard I think this is not the right issue for your problem. However it sounds like you might have set up your repo via ssh while you don't have the proper dependencies for that. Have you tried usinbg the repo via https?

**Comment by kalebo** [comment]
Just for anyone else coming across the above issue with an unsupported URL error, the dependencies that you need that @pReya hints towards should be supplied by `apt install git` if you are on a Debian derivative.

**Comment by jorgen-k** [comment]
Thanks @kalebo I was having the same problem with the docker image not supporting this.

An even easier hook:
```ruby
Gollum::Hook.register(:post_commit, :hook_id) do |committer, sha1|
   `cd /wiki && git pull && git push`
 end
 ```

Perhaps the official docker image could be updated with the right dependencies?
