### ISSUE TITLE
Webrick Error if using pygments and a lexer is not found

### ISSUE THREAD

**Issue by techwiz24** [gollum/gollum-lib#153]
If `pygments` is installed and a page contains a code block that specifies a lexer that does not exist, the page will not load and will throw an exception:

```
2015-05-22 08:32:31 - MentosError - Traceback (most recent call last):
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 303, in start
    res = self.get_data(method, lexer, args, kwargs, text)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 171, in get_data
    res = self.highlight_text(text, lexer, formatter_name, args, _convert_keys(opts))
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 122, in highlight_text
    lexer = self.return_lexer(lexer, args, kwargs, code)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/mentos.py", line 79, in return_lexer
    return lexers.get_lexer_by_name(lexer, **inputs)
  File "/var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/vendor/pygments-main/pygments/lexers/__init__.py", line 98, in get_lexer_by_name
    raise ClassNotFound('no lexer for alias %r found' % _alias)
ClassNotFound: no lexer for alias 'markdown' found
:
        /var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:405:in `header_to_json'
        /var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:287:in `handle_header_and_return'
        /var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:262:in `block in mentos'
        /usr/lib/ruby/1.9.1/timeout.rb:69:in `timeout'
        /var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:233:in `mentos'
        /var/lib/gems/1.9.1/gems/pygments.rb-0.6.3/lib/pygments/popen.rb:215:in `highlight'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.0.3/lib/gollum-lib/filter/code.rb:80:in `block in process'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.0.3/lib/gollum-lib/filter/code.rb:71:in `each'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.0.3/lib/gollum-lib/filter/code.rb:71:in `process'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.0.3/lib/gollum-lib/markup.rb:120:in `block in process_chain'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.0.3/lib/gollum-lib/markup.rb:119:in `each'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.0.3/lib/gollum-lib/markup.rb:119:in `process_chain'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.0.3/lib/gollum-lib/markup.rb:159:in `render'
        /var/lib/gems/1.9.1/gems/gollum-lib-4.0.3/lib/gollum-lib/page.rb:225:in `formatted_data'
        /var/lib/gems/1.9.1/gems/gollum-4.0.0/lib/gollum/app.rb:492:in `show_page_or_file'
        /var/lib/gems/1.9.1/gems/gollum-4.0.0/lib/gollum/app.rb:480:in `block in <class:App>'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
        /var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
        /var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
        /var/lib/gems/1.9.1/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /var/lib/gems/1.9.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/nulllogger.rb:9:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
        /usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
[2015-05-22 08:32:31] ERROR ArgumentError: invalid byte sequence in US-ASCII
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/utils.rb:241:in `gsub'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/utils.rb:241:in `escape_html'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/showexceptions.rb:103:in `h'
        (erb):169:in `block (2 levels) in pretty'
        (erb):168:in `each'
        (erb):168:in `block in pretty'
        (erb):155:in `each'
        (erb):155:in `pretty'
        /usr/lib/ruby/1.9.1/erb.rb:838:in `eval'
        /usr/lib/ruby/1.9.1/erb.rb:838:in `result'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/showexceptions.rb:97:in `pretty'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:30:in `rescue in call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
        /var/lib/gems/1.9.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
        /var/lib/gems/1.9.1/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
        /usr/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
        /usr/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

Found this when investigating gollum/gollum#1015

**Comment by techwiz24** [comment]
Changing [this line](https://github.com/gollum/gollum-lib/blob/7e54ec86ba1e8cd7298de31d2d7583359f913ce2/lib/gollum-lib/filter/code.rb#L80) to read:

```ruby
 hl_code = Pygments.highlight(code, :lexer => lang, :options => { :encoding => encoding.to_s, :startinline => true }) rescue code
```

seems to fix the problem, although this should probably be logged.

If I can get some assistance with #152, I'll write up a PR.

**Comment by techwiz24** [comment]
Using the [asciidoctor](https://github.com/asciidoctor/asciidoctor/commit/ae103e4d9b25cfe3324e0b55f45c36c11dcc0df8)  fix, replacing:

```ruby
hl_code = Pygments.highlight(code, :lexer => lang, :options => { :encoding => encoding.to_s, :startinline => true })
```

with:

```ruby
lexer = Pygments::Lexer[(lang)] || Pygments::Lexer['text']
hl_code = lexer.highlight(code, :options => { :encoding => encoding.to_s, :startinline => true })
```

Seems to have fixed it, although this stops `pygments` from trying to derive what inspector to use by looking at the code.

**EDIT**: This seems to break the live-preview editor, not sure why

**Comment by techwiz24** [comment]
You can ignore my comment about it breaking the live-preview editor, it seems my cache was somehow corrupted and it failed to completely cache one of the JS files for `ace`.

**Comment by bartkamphorst** [comment]
> although this stops pygments from trying to derive what lexer to use by looking at the code.

True, but given [this comment](https://github.com/tmm1/pygments.rb/blob/master/lib/pygments/mentos.py#L72-L74) I wouldn't be too worried about that. :smile:

**Comment by techwiz24** [comment]
Sounds good. Now that I can [get the gem building](https://github.com/gollum/gollum-lib#152) I'll try to get a PR written up this week.

**Comment by bartkamphorst** [comment]
Nice! :+1:

**Comment by techwiz24** [comment]
Huh, so master is [failing a test](https://github.com/gollum/gollum-lib/blob/master/test/test_hook.rb#L93) on my arch machine (this is before making any changes):

```bash
[nathan@nathan-arch gollum-lib]$ bundle exec rake test
/usr/bin/ruby -I"lib:lib:test:."  "/usr/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/test_*.rb" 
Loaded suite /usr/lib/ruby/2.2.0/rake/rake_test_loader
Started
.....................................................................................................................................................
...................F
=====================================================================================================================================================
Failure: test_push_and_pull(Pushing_and_pulling)
/home/nathan/projects/gollum-lib/test/test_hook.rb:93:in `block (2 levels) in <top (required)>'
<false> expected but was
<true>

diff:
? false
? tru  
=====================================================================================================================================================
.................................................................................................

Finished in 3.552655921 seconds.
-----------------------------------------------------------------------------------------------------------------------------------------------------
266 tests, 603 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
99.6241% passed
-----------------------------------------------------------------------------------------------------------------------------------------------------
74.87 tests/s, 169.73 assertions/s
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test:."  "/usr/lib/ruby/2.2.0/rake/rake_test_loader.rb" "test/**/test_*.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)

```

but was passing earlier today on an ubuntu machine. Open a separate bug or ignore it because it's probably my environment?

**Comment by dometto** [comment]
Huh, weird. I'm also getting this on a fresh vagrant box on arch, so yes, please open an issue.

**Comment by techwiz24** [comment]
Do you have an estimate as to when the next release for `gollum` and `gollum-lib` will be cut?

**Comment by dometto** [comment]
We were initially waiting for some some CSS changes to make it into gollum 4.1, so we could also release some of the macros in gollum-lib `rc`, but it looks like that's going to have to wait a bit longer. We can see if we can do a smaller bugfix release at a sooner date though.
